server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27016/mongotestdb?authSource=admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG